<?php
$title='Inventaris'; $u=require_tenant_user();$tid=(int)$u['tenant_id'];
$q=db()->prepare('SELECT * FROM assets WHERE tenant_id=? ORDER BY nama_asset');$q->execute([$tid]);$assets=$q->fetchAll();
$total=array_sum(array_map(fn($x)=>(int)$x['jumlah'],$assets));$baik=array_sum(array_map(fn($x)=>(int)$x['jumlah_baik'],$assets));$rusak=array_sum(array_map(fn($x)=>(int)$x['jumlah_rusak'],$assets));
?>
<div class="page-head"><div><span class="eyebrow dark">Inventaris Tenant</span><h1>Data Alat & Aset</h1><p>Inventaris hanya dapat diakses oleh tenant <?= e($u['nama_tenant']) ?>.</p></div><?php if(is_tenant_admin($u)):?><button class="btn btn-primary" data-open-dialog="asset-dialog">+ Tambah Aset</button><?php endif;?></div>
<div class="metric-grid compact"><article class="metric-card"><span>Total unit</span><strong><?= $total ?></strong><h3>Inventaris</h3></article><article class="metric-card"><span>Kondisi</span><strong><?= $baik ?></strong><h3>Baik</h3></article><article class="metric-card"><span>Perlu perhatian</span><strong><?= $rusak ?></strong><h3>Rusak</h3></article></div>
<section class="panel"><div class="panel-head"><div><h2>Daftar Inventaris</h2><p><?= count($assets) ?> jenis aset tercatat.</p></div><input class="table-search" type="search" placeholder="Cari aset..." data-table-search></div><div class="table-wrap"><table data-search-table><thead><tr><th>Kode</th><th>Nama Aset</th><th>Jumlah</th><th>Kondisi</th><th>Lokasi</th><th>Nilai</th><?php if(is_tenant_admin($u)):?><th>Aksi</th><?php endif;?></tr></thead><tbody><?php if(!$assets):?><tr><td colspan="7" class="empty-cell">Belum ada inventaris.</td></tr><?php endif;?><?php foreach($assets as $a):?><tr><td><?= e($a['kode_asset']) ?></td><td><b><?= e($a['nama_asset']) ?></b><small class="block muted-text"><?= e($a['kategori']??'-') ?></small></td><td><?= (int)$a['jumlah'] ?><small class="block muted-text"><?= (int)$a['jumlah_baik'] ?> baik • <?= (int)$a['jumlah_rusak'] ?> rusak</small></td><td><?= status_badge($a['kondisi']) ?></td><td><?= e($a['lokasi']??'-') ?></td><td><?= rupiah($a['nilai_asset']) ?></td><?php if(is_tenant_admin($u)):?><td><button class="btn-icon" data-edit-asset='<?= e(json_encode($a,JSON_UNESCAPED_UNICODE)) ?>'>Edit</button><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="delete_asset"><input type="hidden" name="asset_id" value="<?= (int)$a['asset_id'] ?>"><button class="btn-icon danger" data-confirm="Hapus aset ini?">Hapus</button></form></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section>
<?php if(is_tenant_admin($u)):?><dialog class="modal" id="asset-dialog"><form method="post" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_asset"><input type="hidden" name="asset_id"><div class="modal-head"><h2>Data Inventaris</h2><button type="button" data-close-dialog>×</button></div><div class="form-grid two"><label>Kode Aset<input name="kode_asset" required></label><label>Nama Aset<input name="nama_asset" required></label><label>Kategori<input name="kategori"></label><label>Jumlah<input type="number" min="1" name="jumlah" value="1"></label><label>Jumlah Baik<input type="number" min="0" name="jumlah_baik" value="1"></label><label>Jumlah Rusak<input type="number" min="0" name="jumlah_rusak" value="0"></label><label>Kondisi<select name="kondisi"><option>BAIK</option><option>RUSAK_RINGAN</option><option>RUSAK_BERAT</option><option>HILANG</option></select></label><label>Lokasi<input name="lokasi"></label><label>Tanggal Perolehan<input type="date" name="tanggal_perolehan"></label><label>Sumber Perolehan<input name="sumber_perolehan"></label><label>Nilai Aset<input type="number" min="0" name="nilai_asset" value="0"></label></div><label>Keterangan<textarea name="keterangan"></textarea></label><div class="modal-actions"><button type="button" class="btn btn-light" data-close-dialog>Batal</button><button class="btn btn-primary">Simpan Aset</button></div></form></dialog><?php endif;?>
