<?php
$title='Keuangan'; $u=require_tenant_user();$tid=(int)$u['tenant_id'];
$q=db()->prepare('SELECT ft.*,pk.nama_proja FROM financial_transactions ft LEFT JOIN program_kerja pk ON pk.proja_id=ft.proja_id WHERE ft.tenant_id=? ORDER BY ft.tanggal_transaksi DESC,ft.transaction_id DESC');$q->execute([$tid]);$rows=$q->fetchAll();
$income=array_sum(array_map(fn($x)=>$x['jenis_transaksi']==='PEMASUKAN'?(float)$x['nominal']:0,$rows));$expense=array_sum(array_map(fn($x)=>$x['jenis_transaksi']==='PENGELUARAN'?(float)$x['nominal']:0,$rows));$saldo=$income-$expense;
$p=db()->prepare('SELECT proja_id,nama_proja FROM program_kerja WHERE tenant_id=? ORDER BY nama_proja');$p->execute([$tid]);$programs=$p->fetchAll();
?>
<div class="page-head"><div><span class="eyebrow dark">Keuangan Tenant</span><h1>Pemasukan & Pengeluaran</h1><p>Ringkasan keuangan dihitung hanya dari transaksi tenant <?= e($u['nama_tenant']) ?>.</p></div><?php if(is_tenant_admin($u)):?><button class="btn btn-primary" data-open-dialog="finance-dialog">+ Tambah Transaksi</button><?php endif;?></div>
<div class="metric-grid compact"><article class="metric-card money-in"><span>Total pemasukan</span><strong><?= rupiah($income) ?></strong><h3>Masuk</h3></article><article class="metric-card money-out"><span>Total pengeluaran</span><strong><?= rupiah($expense) ?></strong><h3>Keluar</h3></article><article class="metric-card"><span>Saldo berjalan</span><strong><?= rupiah($saldo) ?></strong><h3>Saldo</h3></article></div>
<section class="panel"><div class="panel-head"><div><h2>Riwayat Transaksi</h2><p><?= count($rows) ?> transaksi tercatat.</p></div><input class="table-search" type="search" placeholder="Cari transaksi..." data-table-search></div><div class="table-wrap"><table data-search-table><thead><tr><th>Tanggal</th><th>Jenis</th><th>Kategori / Deskripsi</th><th>Program Kerja</th><th>Nominal</th><th>Bukti</th><?php if(is_tenant_admin($u)):?><th>Aksi</th><?php endif;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="7" class="empty-cell">Belum ada transaksi keuangan.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><?= e(indo_date($r['tanggal_transaksi'])) ?></td><td><?= status_badge($r['jenis_transaksi']==='PEMASUKAN'?'ACTIVE':'REJECTED') ?><small class="block muted-text"><?= e($r['jenis_transaksi']) ?></small></td><td><b><?= e($r['kategori']??'-') ?></b><small class="block muted-text"><?= e($r['deskripsi']??'') ?></small></td><td><?= e($r['nama_proja']??'-') ?></td><td class="<?= $r['jenis_transaksi']==='PEMASUKAN'?'money-text-in':'money-text-out' ?>"><?= $r['jenis_transaksi']==='PEMASUKAN'?'+':'-' ?><?= rupiah($r['nominal']) ?></td><td><?= $r['bukti_path']?'<a class="text-link" target="_blank" href="'.e($r['bukti_path']).'">Lihat</a>':'-' ?></td><?php if(is_tenant_admin($u)):?><td><button class="btn-icon" data-edit-finance='<?= e(json_encode($r,JSON_UNESCAPED_UNICODE)) ?>'>Edit</button><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="delete_finance"><input type="hidden" name="transaction_id" value="<?= (int)$r['transaction_id'] ?>"><button class="btn-icon danger" data-confirm="Hapus transaksi ini?">Hapus</button></form></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section>
<?php if(is_tenant_admin($u)):?><dialog class="modal" id="finance-dialog"><form method="post" enctype="multipart/form-data" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_finance"><input type="hidden" name="transaction_id"><div class="modal-head"><h2>Transaksi Keuangan</h2><button type="button" data-close-dialog>×</button></div><div class="form-grid two"><label>Jenis<select name="jenis_transaksi" required><option>PEMASUKAN</option><option>PENGELUARAN</option></select></label><label>Tanggal<input type="date" name="tanggal_transaksi" value="<?= date('Y-m-d') ?>" required></label><label>Kategori<input name="kategori" placeholder="Iuran / konsumsi / dll"></label><label>Nominal<input type="number" min="1" name="nominal" required></label><label>Program Kerja<select name="proja_id"><option value="">Tidak terkait proja</option><?php foreach($programs as $p):?><option value="<?= (int)$p['proja_id'] ?>"><?= e($p['nama_proja']) ?></option><?php endforeach;?></select></label><label>Bukti<input type="file" name="bukti" accept=".pdf,.jpg,.jpeg,.png"></label></div><label>Deskripsi<textarea name="deskripsi"></textarea></label><div class="modal-actions"><button type="button" class="btn btn-light" data-close-dialog>Batal</button><button class="btn btn-primary">Simpan Transaksi</button></div></form></dialog><?php endif;?>
