<?php
$title='Data Anggota'; $u=require_tenant_user(); $tid=(int)$u['tenant_id'];
$s=db()->prepare('SELECT m.*,ps.nama_prodi,ps.jenjang FROM members m LEFT JOIN program_studi ps ON ps.prodi_id=m.prodi_id WHERE m.tenant_id=? ORDER BY m.status,m.nama_lengkap');$s->execute([$tid]);$members=$s->fetchAll();
$prodi=[]; if($u['jurusan_id']){$p=db()->prepare('SELECT prodi_id,jenjang,nama_prodi FROM program_studi WHERE jurusan_id=? AND status=\'AKTIF\' ORDER BY nama_prodi');$p->execute([$u['jurusan_id']]);$prodi=$p->fetchAll();}
?>
<div class="page-head"><div><span class="eyebrow dark">Data Tenant</span><h1>Anggota Organisasi</h1><p>Semua data pada halaman ini otomatis dibatasi oleh tenant <b><?= e($u['nama_tenant']) ?></b>.</p></div><?php if(is_tenant_admin($u)):?><button class="btn btn-primary" data-open-dialog="member-dialog">+ Tambah Anggota</button><?php endif;?></div>
<div class="metric-grid compact"><article class="metric-card"><span>Total data</span><strong><?= count($members) ?></strong><h3>Anggota</h3></article><article class="metric-card"><span>Status aktif</span><strong><?= count(array_filter($members,fn($x)=>$x['status']==='AKTIF')) ?></strong><h3>Aktif</h3></article><article class="metric-card"><span>Angkatan berbeda</span><strong><?= count(array_unique(array_filter(array_column($members,'angkatan')))) ?></strong><h3>Angkatan</h3></article></div>
<section class="panel"><div class="panel-head"><div><h2>Daftar Anggota</h2><p>Gunakan pencarian untuk menemukan anggota.</p></div><input class="table-search" type="search" placeholder="Cari nama / NPM..." data-table-search></div><div class="table-wrap"><table data-search-table><thead><tr><th>NPM</th><th>Nama</th><th>Prodi</th><th>Angkatan</th><th>Kontak</th><th>Status</th><?php if(is_tenant_admin($u)):?><th>Aksi</th><?php endif;?></tr></thead><tbody><?php if(!$members):?><tr><td colspan="7" class="empty-cell">Belum ada data anggota.</td></tr><?php endif;?><?php foreach($members as $m):?><tr><td><?= e($m['npm']??'-') ?></td><td><b><?= e($m['nama_lengkap']) ?></b><small class="block muted-text"><?= $m['jenis_kelamin']==='L'?'Laki-laki':($m['jenis_kelamin']==='P'?'Perempuan':'-') ?></small></td><td><?= e(($m['jenjang']??'').' '.($m['nama_prodi']??'-')) ?></td><td><?= e($m['angkatan']??'-') ?></td><td><?= e($m['email']??'-') ?><small class="block muted-text"><?= e($m['no_hp']??'') ?></small></td><td><?= status_badge($m['status']) ?></td><?php if(is_tenant_admin($u)):?><td><button class="btn-icon" data-edit-member='<?= e(json_encode($m,JSON_UNESCAPED_UNICODE)) ?>'>Edit</button><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="delete_member"><input type="hidden" name="member_id" value="<?= (int)$m['member_id'] ?>"><button class="btn-icon danger" data-confirm="Hapus anggota ini?">Hapus</button></form></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section>
<?php if(is_tenant_admin($u)):?><dialog class="modal" id="member-dialog"><form method="post" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_member"><input type="hidden" name="member_id" value=""><div class="modal-head"><div><h2>Data Anggota</h2><p>Tambah atau ubah data anggota tenant.</p></div><button type="button" class="modal-close" data-close-dialog>×</button></div><div class="form-grid two"><label>NPM<input name="npm" placeholder="2478xxxx"></label><label>Nama Lengkap<input name="nama_lengkap" required></label><label>Jenis Kelamin<select name="jenis_kelamin"><option value="">-</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label><label>Angkatan<input type="number" name="angkatan" min="2000" max="2100"></label><?php if($prodi):?><label>Program Studi<select name="prodi_id"><option value="">Pilih prodi</option><?php foreach($prodi as $p):?><option value="<?= (int)$p['prodi_id'] ?>"><?= e($p['jenjang'].' '.$p['nama_prodi']) ?></option><?php endforeach;?></select></label><?php endif;?><label>Status<select name="status"><option>AKTIF</option><option>NONAKTIF</option><option>ALUMNI</option></select></label><label>Email<input type="email" name="email"></label><label>No. HP<input name="no_hp"></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-dialog>Batal</button><button class="btn btn-primary">Simpan Data</button></div></form></dialog><?php endif;?>
