<?php
$title='Pesan HMJ–HIMA';$u=require_tenant_user();$tid=(int)$u['tenant_id'];
if(!in_array(($u['tenant_type']??''),['HMJ','HIMA'],true)){http_response_code(403);exit('Fitur pesan hanya untuk HMJ dan HIMA.');}
if($u['tenant_type']==='HIMA'){$q=db()->prepare("SELECT tenant_id,nama_tenant FROM tenants WHERE tenant_id=? AND tenant_type='HMJ' AND status='ACTIVE'");$q->execute([$u['parent_tenant_id']]);$peers=$q->fetchAll();}
else{$q=db()->prepare("SELECT tenant_id,nama_tenant FROM tenants WHERE parent_tenant_id=? AND tenant_type='HIMA' AND status='ACTIVE' ORDER BY nama_tenant");$q->execute([$tid]);$peers=$q->fetchAll();}
$q=db()->prepare('SELECT tm.*,s.nama_tenant sender_name,r.nama_tenant receiver_name,u.nama_lengkap sender_user FROM tenant_messages tm JOIN tenants s ON s.tenant_id=tm.sender_tenant_id JOIN tenants r ON r.tenant_id=tm.receiver_tenant_id JOIN users u ON u.user_id=tm.sender_user_id WHERE tm.sender_tenant_id=? OR tm.receiver_tenant_id=? ORDER BY tm.sent_at DESC LIMIT 100');$q->execute([$tid,$tid]);$messages=$q->fetchAll();
db()->prepare('UPDATE tenant_messages SET is_read=1,read_at=COALESCE(read_at,NOW()) WHERE receiver_tenant_id=? AND is_read=0')->execute([$tid]);
?>
<div class="page-head"><div><span class="eyebrow dark">Komunikasi Terbatas</span><h1>Pesan HMJ ↔ HIMA</h1><p>Sistem hanya mengizinkan komunikasi antara HIMA dengan HMJ induknya. Komunikasi antartenant lain ditolak oleh trigger database.</p></div><button class="btn btn-primary" data-open-dialog="message-dialog" <?= !$peers?'disabled':'' ?>>+ Tulis Pesan</button></div>
<div class="message-layout"><aside class="panel"><div class="panel-head"><div><h2>Relasi Diizinkan</h2><p><?= count($peers) ?> tenant dapat dihubungi.</p></div></div><div class="peer-list"><?php if(!$peers):?><div class="empty-state compact">Belum ada HIMA aktif yang terhubung.</div><?php endif;?><?php foreach($peers as $p):?><button data-compose-to="<?= (int)$p['tenant_id'] ?>"><span class="avatar-sm"><?= e(strtoupper(substr($p['nama_tenant'],0,1))) ?></span><span><b><?= e($p['nama_tenant']) ?></b><small><?= $u['tenant_type']==='HMJ'?'HIMA di bawah HMJ':'HMJ induk' ?></small></span></button><?php endforeach;?></div></aside><section class="panel"><div class="panel-head"><div><h2>Riwayat Pesan</h2><p>100 pesan terbaru.</p></div></div><div class="message-list"><?php if(!$messages):?><div class="empty-state">Belum ada pesan.</div><?php endif;?><?php foreach($messages as $m):$mine=(int)$m['sender_tenant_id']===$tid;?><article class="message-item <?= $mine?'mine':'incoming' ?>"><div class="message-meta"><b><?= e($mine?'Anda → '.$m['receiver_name']:$m['sender_name']) ?></b><span><?= e(indo_date($m['sent_at'],'d M Y H:i')) ?></span></div><?php if($m['subject']):?><h3><?= e($m['subject']) ?></h3><?php endif;?><p><?= nl2br(e($m['message'])) ?></p></article><?php endforeach;?></div></section></div>
<dialog class="modal" id="message-dialog"><form method="post" class="modal-card small"><?= csrf_field() ?><input type="hidden" name="action" value="send_message"><div class="modal-head"><h2>Tulis Pesan</h2><button type="button" data-close-dialog>×</button></div><label>Penerima<select name="receiver_tenant_id" required><option value="">Pilih tenant</option><?php foreach($peers as $p):?><option value="<?= (int)$p['tenant_id'] ?>"><?= e($p['nama_tenant']) ?></option><?php endforeach;?></select></label><label>Subjek<input name="subject"></label><label>Pesan<textarea name="message" rows="6" required></textarea></label><div class="modal-actions"><button class="btn btn-primary">Kirim Pesan</button></div></form></dialog>
