<?php
$title='Program Kerja'; $u=require_login();
$programs=[];$review=[];$own=false;
if(is_super_admin($u)){
 $programs=db()->query("SELECT pk.*,t.nama_tenant,t.tenant_type FROM program_kerja pk JOIN tenants t ON t.tenant_id=pk.tenant_id WHERE t.tenant_type IN('ORMAWA','HMJ') ORDER BY pk.created_at DESC")->fetchAll();
 $review=array_values(array_filter($programs,fn($x)=>$x['status_proja']==='DIAJUKAN'));
}else{
 $tid=(int)$u['tenant_id'];$own=true;
 $q=db()->prepare('SELECT pk.*,t.nama_tenant,t.tenant_type FROM program_kerja pk JOIN tenants t ON t.tenant_id=pk.tenant_id WHERE pk.tenant_id=? ORDER BY pk.created_at DESC');$q->execute([$tid]);$programs=$q->fetchAll();
 if(($u['tenant_type']??'')==='HMJ'){
  $r=db()->prepare("SELECT pk.*,t.nama_tenant,t.tenant_type,t.parent_tenant_id FROM program_kerja pk JOIN tenants t ON t.tenant_id=pk.tenant_id WHERE t.tenant_type='HIMA' AND t.parent_tenant_id=? AND pk.status_proja='DIAJUKAN' ORDER BY pk.created_at");$r->execute([$tid]);$review=$r->fetchAll();
 }
}
?>
<div class="page-head"><div><span class="eyebrow dark">Program Kerja</span><h1><?= is_super_admin($u)?'Monitoring Program Kerja ORMAWA & HMJ':'Program Kerja '.$u['nama_tenant'] ?></h1><p><?= is_super_admin($u)?'Super Admin dapat memantau dan meninjau proja ORMAWA/HMJ.':'Program kerja tenant disimpan terpisah menggunakan tenant_id.' ?></p></div><?php if($own&&is_tenant_admin($u)):?><button class="btn btn-primary" data-open-dialog="program-dialog">+ Tambah Program</button><?php endif;?></div>
<?php if($review):?><section class="panel review-panel"><div class="panel-head"><div><h2>Menunggu Peninjauan</h2><p><?= count($review) ?> program kerja diajukan.</p></div></div><div class="review-grid"><?php foreach($review as $r):?><article class="review-card"><span class="tenant-type-chip <?= strtolower($r['tenant_type']) ?>"><?= e($r['tenant_type']) ?></span><h3><?= e($r['nama_proja']) ?></h3><p><b><?= e($r['nama_tenant']) ?></b> • <?= e(indo_date($r['tanggal_mulai'])) ?></p><p><?= e($r['deskripsi']??'Tanpa deskripsi') ?></p><div class="review-meta"><span><?= rupiah($r['estimasi_anggaran']) ?></span><span><?= e($r['lokasi']??'-') ?></span></div><form method="post" class="review-form"><?= csrf_field() ?><input type="hidden" name="action" value="review_program"><input type="hidden" name="proja_id" value="<?= (int)$r['proja_id'] ?>"><input type="text" name="catatan_review" placeholder="Catatan review"><div><button class="btn btn-success btn-sm" name="decision" value="DISETUJUI">Setujui</button><button class="btn btn-light btn-sm" name="decision" value="REVISI">Revisi</button><button class="btn btn-danger-soft btn-sm" name="decision" value="DITOLAK">Tolak</button></div></form></article><?php endforeach;?></div></section><?php endif;?>
<section class="panel"><div class="panel-head"><div><h2>Daftar Program Kerja</h2><p><?= count($programs) ?> program tercatat.</p></div><input class="table-search" type="search" placeholder="Cari program..." data-table-search></div><div class="table-wrap"><table data-search-table><thead><tr><th>Program</th><th>Tenant</th><th>Jadwal</th><th>Anggaran</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$programs):?><tr><td colspan="6" class="empty-cell">Belum ada program kerja.</td></tr><?php endif;?><?php foreach($programs as $p):?><tr><td><b><?= e($p['nama_proja']) ?></b><small class="block muted-text"><?= e($p['penanggung_jawab']??'-') ?> • <?= e($p['lokasi']??'-') ?></small></td><td><?= e($p['nama_tenant']) ?><small class="block muted-text"><?= e($p['tenant_type']) ?></small></td><td><?= e(indo_date($p['tanggal_mulai'])) ?><small class="block muted-text">s.d. <?= e(indo_date($p['tanggal_selesai'])) ?></small></td><td><?= rupiah($p['estimasi_anggaran']) ?></td><td><?= status_badge($p['status_proja']) ?></td><td><?php if($own && (int)$p['tenant_id']===(int)$u['tenant_id'] && is_tenant_admin($u)):?><?php if(in_array($p['status_proja'],['DRAFT','REVISI'],true)):?><button class="btn-icon" data-edit-program='<?= e(json_encode($p,JSON_UNESCAPED_UNICODE)) ?>'>Edit</button><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="submit_program"><input type="hidden" name="proja_id" value="<?= (int)$p['proja_id'] ?>"><button class="btn-icon success">Ajukan</button></form><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="delete_program"><input type="hidden" name="proja_id" value="<?= (int)$p['proja_id'] ?>"><button class="btn-icon danger" data-confirm="Hapus program kerja ini?">Hapus</button></form><?php elseif($p['status_proja']==='DISETUJUI'):?><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="change_program_status"><input type="hidden" name="proja_id" value="<?= (int)$p['proja_id'] ?>"><input type="hidden" name="status_proja" value="BERJALAN"><button class="btn-icon success">Mulai</button></form><?php elseif($p['status_proja']==='BERJALAN'):?><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="change_program_status"><input type="hidden" name="proja_id" value="<?= (int)$p['proja_id'] ?>"><input type="hidden" name="status_proja" value="SELESAI"><button class="btn-icon success">Selesai</button></form><?php else:?><span class="muted-text">—</span><?php endif;?><?php else:?><span class="muted-text">Monitor</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if($own&&is_tenant_admin($u)):?><dialog class="modal" id="program-dialog"><form method="post" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_program"><input type="hidden" name="proja_id"><div class="modal-head"><div><h2>Program Kerja</h2><p>Program baru disimpan sebagai DRAFT.</p></div><button type="button" data-close-dialog>×</button></div><label>Nama Program Kerja<input name="nama_proja" required></label><div class="form-grid two"><label>Tanggal Mulai<input type="date" name="tanggal_mulai"></label><label>Tanggal Selesai<input type="date" name="tanggal_selesai"></label><label>Lokasi<input name="lokasi"></label><label>Penanggung Jawab<input name="penanggung_jawab"></label><label>Estimasi Anggaran<input type="number" min="0" name="estimasi_anggaran" value="0"></label></div><label>Deskripsi<textarea name="deskripsi" rows="3"></textarea></label><label>Tujuan<textarea name="tujuan" rows="3"></textarea></label><div class="modal-actions"><button type="button" class="btn btn-light" data-close-dialog>Batal</button><button class="btn btn-primary">Simpan DRAFT</button></div></form></dialog><?php endif;?>
