<?php
$title='Struktur Organisasi'; $u=require_login();
$viewTenant=request_int('tenant_id');
if(!$viewTenant) $viewTenant=(int)($u['tenant_id']??0);
if(!$viewTenant){$first=db()->query("SELECT tenant_id FROM tenants WHERE tenant_type IN('ORMAWA','HMJ') AND status='ACTIVE' ORDER BY tenant_type,nama_tenant LIMIT 1")->fetchColumn();$viewTenant=(int)$first;}
if(!$viewTenant || !can_view_tenant($viewTenant,$u)) {http_response_code(403);exit('Anda tidak dapat melihat struktur tenant tersebut.');}
$t=db()->prepare('SELECT t.*,j.nama_jurusan,ps.nama_prodi FROM tenants t LEFT JOIN jurusan j ON j.jurusan_id=t.jurusan_id LEFT JOIN program_studi ps ON ps.prodi_id=t.prodi_id WHERE t.tenant_id=?');$t->execute([$viewTenant]);$tenant=$t->fetch();
$canManage=can_manage_tenant($viewTenant,$u);
$periodStmt=db()->prepare('SELECT * FROM organization_periods WHERE tenant_id=? ORDER BY tanggal_mulai DESC');$periodStmt->execute([$viewTenant]);$periods=$periodStmt->fetchAll();
$positionStmt=db()->prepare('SELECT * FROM positions WHERE tenant_id=? ORDER BY urutan,nama_jabatan');$positionStmt->execute([$viewTenant]);$positions=$positionStmt->fetchAll();
$memberStmt=db()->prepare("SELECT * FROM members WHERE tenant_id=? AND status='AKTIF' ORDER BY nama_lengkap");$memberStmt->execute([$viewTenant]);$members=$memberStmt->fetchAll();
$structStmt=db()->prepare('SELECT os.structure_id,os.mulai_jabatan,os.selesai_jabatan,m.nama_lengkap,m.npm,p.nama_jabatan,p.urutan,op.nama_periode FROM organization_structures os JOIN members m ON m.member_id=os.member_id JOIN positions p ON p.position_id=os.position_id JOIN organization_periods op ON op.period_id=os.period_id WHERE os.tenant_id=? ORDER BY op.tanggal_mulai DESC,p.urutan,m.nama_lengkap');$structStmt->execute([$viewTenant]);$structures=$structStmt->fetchAll();
$choices=[];if(is_super_admin($u)){$choices=db()->query("SELECT tenant_id,nama_tenant FROM tenants WHERE tenant_type IN('ORMAWA','HMJ') AND status='ACTIVE' ORDER BY tenant_type,nama_tenant")->fetchAll();}elseif(($u['tenant_type']??'')==='HMJ'){$q=db()->prepare("SELECT tenant_id,nama_tenant FROM tenants WHERE tenant_id=? OR (tenant_type='HIMA' AND parent_tenant_id=?) ORDER BY tenant_type,nama_tenant");$q->execute([$u['tenant_id'],$u['tenant_id']]);$choices=$q->fetchAll();}
?>
<div class="page-head"><div><span class="eyebrow dark">Struktur Organisasi</span><h1><?= e($tenant['nama_tenant']) ?></h1><p><?= e($tenant['nama_jurusan']??($tenant['tenant_type'].' tenant')) ?><?= $tenant['nama_prodi']?' • '.e($tenant['nama_prodi']):'' ?></p></div><?php if($choices):?><form method="get"><input type="hidden" name="page" value="structure"><select class="tenant-switch" name="tenant_id" onchange="this.form.submit()"><?php foreach($choices as $c):?><option value="<?= (int)$c['tenant_id'] ?>" <?= (int)$c['tenant_id']===$viewTenant?'selected':'' ?>><?= e($c['nama_tenant']) ?></option><?php endforeach;?></select></form><?php endif;?></div>
<?php if($canManage):?><div class="toolbar"><button class="btn btn-light" data-open-dialog="period-dialog">+ Periode</button><button class="btn btn-light" data-open-dialog="position-dialog">+ Jabatan</button><button class="btn btn-primary" data-open-dialog="structure-dialog">+ Tambah Pengurus</button></div><?php endif;?>
<section class="panel"><div class="panel-head"><div><h2>Susunan Pengurus</h2><p>Struktur ditampilkan berdasarkan periode dan urutan jabatan.</p></div></div><div class="org-chart"><?php if(!$structures):?><div class="empty-state">Struktur organisasi belum diisi.</div><?php endif;?><?php $last='';foreach($structures as $s):if($last!==$s['nama_periode']){if($last!=='')echo '</div></div>'; $last=$s['nama_periode'];echo '<div class="org-period"><h3>'.e($last).'</h3><div class="org-people">';}?><article class="person-card"><span class="person-avatar"><?= e(strtoupper(substr($s['nama_lengkap'],0,1))) ?></span><div><small><?= e($s['nama_jabatan']) ?></small><h4><?= e($s['nama_lengkap']) ?></h4><p><?= e($s['npm']??'') ?></p></div><?php if($canManage):?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete_structure"><input type="hidden" name="structure_id" value="<?= (int)$s['structure_id'] ?>"><button class="person-delete" data-confirm="Hapus dari struktur?">×</button></form><?php endif;?></article><?php endforeach;if($last!=='')echo '</div></div>';?></div></section>
<?php if($canManage):?>
<dialog class="modal" id="period-dialog"><form method="post" class="modal-card small"><?= csrf_field() ?><input type="hidden" name="action" value="save_period"><div class="modal-head"><h2>Tambah Periode</h2><button type="button" data-close-dialog>×</button></div><label>Nama Periode<input name="nama_periode" placeholder="Periode 2026/2027" required></label><div class="form-grid two"><label>Mulai<input type="date" name="tanggal_mulai" required></label><label>Selesai<input type="date" name="tanggal_selesai" required></label></div><label>Status<select name="status"><option>AKTIF</option><option>SELESAI</option></select></label><div class="modal-actions"><button class="btn btn-primary">Simpan</button></div></form></dialog>
<dialog class="modal" id="position-dialog"><form method="post" class="modal-card small"><?= csrf_field() ?><input type="hidden" name="action" value="save_position"><div class="modal-head"><h2>Tambah Jabatan</h2><button type="button" data-close-dialog>×</button></div><label>Nama Jabatan<input name="nama_jabatan" required placeholder="Ketua"></label><label>Urutan<input type="number" name="urutan" value="1" min="0"></label><div class="modal-actions"><button class="btn btn-primary">Simpan</button></div></form></dialog>
<dialog class="modal" id="structure-dialog"><form method="post" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_structure"><div class="modal-head"><h2>Tambah Pengurus</h2><button type="button" data-close-dialog>×</button></div><div class="form-grid two"><label>Periode<select name="period_id" required><option value="">Pilih periode</option><?php foreach($periods as $p):?><option value="<?= (int)$p['period_id'] ?>"><?= e($p['nama_periode']) ?></option><?php endforeach;?></select></label><label>Jabatan<select name="position_id" required><option value="">Pilih jabatan</option><?php foreach($positions as $p):?><option value="<?= (int)$p['position_id'] ?>"><?= e($p['nama_jabatan']) ?></option><?php endforeach;?></select></label><label>Anggota<select name="member_id" required><option value="">Pilih anggota</option><?php foreach($members as $m):?><option value="<?= (int)$m['member_id'] ?>"><?= e($m['nama_lengkap']) ?></option><?php endforeach;?></select></label><label>Mulai Jabatan<input type="date" name="mulai_jabatan"></label><label>Selesai Jabatan<input type="date" name="selesai_jabatan"></label></div><div class="modal-actions"><button class="btn btn-primary">Masukkan ke Struktur</button></div></form></dialog>
<?php endif;?>
