<?php
$title='Pengajuan'; $u=require_tenant_user();$tid=(int)$u['tenant_id'];
$p=db()->prepare('SELECT proja_id,nama_proja,status_proja FROM program_kerja WHERE tenant_id=? ORDER BY created_at DESC');$p->execute([$tid]);$programs=$p->fetchAll();
$q=db()->prepare('SELECT pp.*,pk.nama_proja FROM program_proposals pp JOIN program_kerja pk ON pk.proja_id=pp.proja_id WHERE pp.tenant_id=? ORDER BY pp.tanggal_pengajuan DESC');$q->execute([$tid]);$proposals=$q->fetchAll();
$q=db()->prepare('SELECT pn.*,pk.nama_proja FROM program_needs pn JOIN program_kerja pk ON pk.proja_id=pn.proja_id WHERE pn.tenant_id=? ORDER BY pn.created_at DESC');$q->execute([$tid]);$needs=$q->fetchAll();
$q=db()->prepare('SELECT pfr.*,pk.nama_proja FROM program_finance_requests pfr JOIN program_kerja pk ON pk.proja_id=pfr.proja_id WHERE pfr.tenant_id=? ORDER BY pfr.created_at DESC');$q->execute([$tid]);$finreq=$q->fetchAll();
$incoming=[];
if(($u['tenant_type']??'')==='HMJ'){
 $sql="SELECT 'proposal' kind,pp.proposal_id id,pp.status,pp.tanggal_pengajuan created_at,pp.judul_proposal title,t.nama_tenant,pk.nama_proja FROM program_proposals pp JOIN tenants t ON t.tenant_id=pp.tenant_id JOIN program_kerja pk ON pk.proja_id=pp.proja_id WHERE t.parent_tenant_id=? AND pp.status='DIAJUKAN'
 UNION ALL SELECT 'need',pn.need_id,pn.status,pn.created_at,pn.judul_pengajuan,t.nama_tenant,pk.nama_proja FROM program_needs pn JOIN tenants t ON t.tenant_id=pn.tenant_id JOIN program_kerja pk ON pk.proja_id=pn.proja_id WHERE t.parent_tenant_id=? AND pn.status='DIAJUKAN'
 UNION ALL SELECT 'finance',pfr.finance_request_id,pfr.status,pfr.created_at,CONCAT('Pengajuan ',pfr.jenis_pengajuan),t.nama_tenant,pk.nama_proja FROM program_finance_requests pfr JOIN tenants t ON t.tenant_id=pfr.tenant_id JOIN program_kerja pk ON pk.proja_id=pfr.proja_id WHERE t.parent_tenant_id=? AND pfr.status='DIAJUKAN' ORDER BY created_at DESC";
 $i=db()->prepare($sql);$i->execute([$tid,$tid,$tid]);$incoming=$i->fetchAll();
}
?>
<div class="page-head"><div><span class="eyebrow dark">Administrasi Program Kerja</span><h1>Proposal, Kebutuhan & Keuangan</h1><p>Semua pengajuan dikaitkan dengan program kerja tenant.</p></div><?php if(is_tenant_admin($u)):?><div class="toolbar"><button class="btn btn-light" data-open-dialog="proposal-dialog">+ Proposal</button><button class="btn btn-light" data-open-dialog="need-dialog">+ Kebutuhan</button><button class="btn btn-primary" data-open-dialog="finance-request-dialog">+ Pengajuan Dana</button></div><?php endif;?></div>
<?php if($incoming):?><section class="panel"><div class="panel-head"><div><h2>Pengajuan HIMA Menunggu Review</h2><p>HMJ hanya melihat pengajuan dari HIMA di bawahnya.</p></div></div><div class="review-grid"><?php foreach($incoming as $r):?><article class="review-card"><span class="tenant-type-chip hima">HIMA</span><h3><?= e($r['title']) ?></h3><p><b><?= e($r['nama_tenant']) ?></b> • <?= e($r['nama_proja']) ?></p><small><?= e(indo_date($r['created_at'],'d M Y H:i')) ?></small><form method="post" class="review-form"><?= csrf_field() ?><input type="hidden" name="action" value="review_submission"><input type="hidden" name="kind" value="<?= e($r['kind']) ?>"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input name="catatan_review" placeholder="Catatan review"><div><button class="btn btn-success btn-sm" name="decision" value="DITERIMA">Terima</button><button class="btn btn-light btn-sm" name="decision" value="REVISI">Revisi</button><button class="btn btn-danger-soft btn-sm" name="decision" value="DITOLAK">Tolak</button></div></form></article><?php endforeach;?></div></section><?php endif;?>
<div class="tabs" data-tabs><button class="active" data-tab="proposal">Proposal <span><?= count($proposals) ?></span></button><button data-tab="need">Kebutuhan <span><?= count($needs) ?></span></button><button data-tab="finance">Pengajuan Keuangan <span><?= count($finreq) ?></span></button></div>
<section class="panel tab-panel active" data-tab-panel="proposal"><div class="table-wrap"><table><thead><tr><th>Proposal</th><th>Program Kerja</th><th>Tanggal</th><th>Status</th><th>File</th></tr></thead><tbody><?php if(!$proposals):?><tr><td colspan="5" class="empty-cell">Belum ada proposal.</td></tr><?php endif;?><?php foreach($proposals as $r):?><tr><td><b><?= e($r['judul_proposal']) ?></b><small class="block muted-text"><?= e($r['nomor_proposal']??'-') ?></small></td><td><?= e($r['nama_proja']) ?></td><td><?= e(indo_date($r['tanggal_pengajuan'])) ?></td><td><?= status_badge($r['status']) ?></td><td><?= $r['file_path']?'<a class="text-link" target="_blank" href="'.e($r['file_path']).'">Buka file</a>':'-' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel tab-panel" data-tab-panel="need"><div class="table-wrap"><table><thead><tr><th>Pengajuan</th><th>Program Kerja</th><th>Estimasi</th><th>Status</th></tr></thead><tbody><?php if(!$needs):?><tr><td colspan="4" class="empty-cell">Belum ada pengajuan kebutuhan.</td></tr><?php endif;?><?php foreach($needs as $r):?><tr><td><b><?= e($r['judul_pengajuan']) ?></b><small class="block muted-text"><?= e($r['keterangan']??'') ?></small></td><td><?= e($r['nama_proja']) ?></td><td><?= rupiah($r['total_estimasi']) ?></td><td><?= status_badge($r['status']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel tab-panel" data-tab-panel="finance"><div class="table-wrap"><table><thead><tr><th>Jenis</th><th>Program Kerja</th><th>Nominal</th><th>Status</th><th>File</th></tr></thead><tbody><?php if(!$finreq):?><tr><td colspan="5" class="empty-cell">Belum ada pengajuan keuangan.</td></tr><?php endif;?><?php foreach($finreq as $r):?><tr><td><b><?= e($r['jenis_pengajuan']) ?></b><small class="block muted-text"><?= e($r['keterangan']??'') ?></small></td><td><?= e($r['nama_proja']) ?></td><td><?= rupiah($r['nominal']) ?></td><td><?= status_badge($r['status']) ?></td><td><?= $r['file_pendukung']?'<a class="text-link" target="_blank" href="'.e($r['file_pendukung']).'">Buka file</a>':'-' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if(is_tenant_admin($u)):?>
<dialog class="modal" id="proposal-dialog"><form method="post" enctype="multipart/form-data" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_proposal"><div class="modal-head"><h2>Ajukan Proposal</h2><button type="button" data-close-dialog>×</button></div><label>Program Kerja<select name="proja_id" required><option value="">Pilih program</option><?php foreach($programs as $p):?><option value="<?= (int)$p['proja_id'] ?>"><?= e($p['nama_proja']) ?></option><?php endforeach;?></select></label><div class="form-grid two"><label>Nomor Proposal<input name="nomor_proposal"></label><label>Judul Proposal<input name="judul_proposal" required></label></div><label>File PDF/JPG/PNG<input type="file" name="file_proposal" accept=".pdf,.jpg,.jpeg,.png"></label><div class="modal-actions"><button class="btn btn-primary">Kirim Proposal</button></div></form></dialog>
<dialog class="modal" id="need-dialog"><form method="post" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_need"><div class="modal-head"><h2>Pengajuan Kebutuhan</h2><button type="button" data-close-dialog>×</button></div><label>Program Kerja<select name="proja_id" required><option value="">Pilih program</option><?php foreach($programs as $p):?><option value="<?= (int)$p['proja_id'] ?>"><?= e($p['nama_proja']) ?></option><?php endforeach;?></select></label><label>Judul Pengajuan<input name="judul_pengajuan" required></label><label>Keterangan<textarea name="keterangan"></textarea></label><div class="form-grid two"><label>Total Estimasi<input type="number" min="0" name="total_estimasi" value="0"></label><label>Item Utama<input name="nama_kebutuhan" placeholder="Contoh: Sewa sound"></label><label>Jumlah<input type="number" step="0.01" name="jumlah" value="1"></label><label>Satuan<input name="satuan" placeholder="unit / box"></label><label>Harga Estimasi<input type="number" min="0" name="harga_estimasi" value="0"></label></div><div class="modal-actions"><button class="btn btn-primary">Kirim Pengajuan</button></div></form></dialog>
<dialog class="modal" id="finance-request-dialog"><form method="post" enctype="multipart/form-data" class="modal-card"><?= csrf_field() ?><input type="hidden" name="action" value="save_finance_request"><div class="modal-head"><h2>Pengajuan Keuangan</h2><button type="button" data-close-dialog>×</button></div><label>Program Kerja<select name="proja_id" required><option value="">Pilih program</option><?php foreach($programs as $p):?><option value="<?= (int)$p['proja_id'] ?>"><?= e($p['nama_proja']) ?></option><?php endforeach;?></select></label><div class="form-grid two"><label>Jenis<select name="jenis_pengajuan"><option>DANA</option><option>REIMBURSE</option><option>LAINNYA</option></select></label><label>Nominal<input type="number" min="1" name="nominal" required></label></div><label>Keterangan<textarea name="keterangan"></textarea></label><label>File Pendukung<input type="file" name="file_pendukung" accept=".pdf,.jpg,.jpeg,.png"></label><div class="modal-actions"><button class="btn btn-primary">Kirim Pengajuan</button></div></form></dialog>
<?php endif;?>
