<?php
$title='Tenant & Persetujuan'; $u=require_login();
$tenants=[];$approvals=[];$children=[];
if(is_super_admin($u)){
 $tenants=db()->query("SELECT t.*,j.nama_jurusan,ps.nama_prodi,p.nama_tenant parent_hmj,(SELECT COUNT(*) FROM users x WHERE x.tenant_id=t.tenant_id AND x.role='ADMIN_TENANT' AND x.status='ACTIVE') admin_count FROM tenants t LEFT JOIN jurusan j ON j.jurusan_id=t.jurusan_id LEFT JOIN program_studi ps ON ps.prodi_id=t.prodi_id LEFT JOIN tenants p ON p.tenant_id=t.parent_tenant_id ORDER BY FIELD(t.tenant_type,'ORMAWA','HMJ','HIMA'),t.nama_tenant")->fetchAll();
 $approvals=db()->query("SELECT ta.*,t.nama_tenant,t.tenant_type,u.nama_lengkap,u.email FROM tenant_approvals ta JOIN tenants t ON t.tenant_id=ta.tenant_id LEFT JOIN users u ON u.user_id=ta.requested_by WHERE ta.status='PENDING' AND ta.approval_target='SUPER_ADMIN' ORDER BY ta.requested_at")->fetchAll();
}else{
 if(($u['tenant_type']??'')!=='HMJ'){http_response_code(403);exit('Halaman ini hanya untuk Super Admin atau HMJ.');}
 $s=db()->prepare("SELECT t.*,ps.jenjang,ps.nama_prodi,(SELECT COUNT(*) FROM users x WHERE x.tenant_id=t.tenant_id AND x.role='ADMIN_TENANT' AND x.status='ACTIVE') admin_count FROM tenants t LEFT JOIN program_studi ps ON ps.prodi_id=t.prodi_id WHERE t.tenant_type='HIMA' AND t.parent_tenant_id=? ORDER BY ps.nama_prodi");$s->execute([$u['tenant_id']]);$children=$s->fetchAll();
 $a=db()->prepare("SELECT ta.*,t.nama_tenant,t.tenant_type,ps.nama_prodi,u.nama_lengkap,u.email FROM tenant_approvals ta JOIN tenants t ON t.tenant_id=ta.tenant_id LEFT JOIN program_studi ps ON ps.prodi_id=t.prodi_id LEFT JOIN users u ON u.user_id=ta.requested_by WHERE ta.status='PENDING' AND ta.approval_target='PARENT_HMJ' AND ta.reviewer_tenant_id=? ORDER BY ta.requested_at");$a->execute([$u['tenant_id']]);$approvals=$a->fetchAll();
}
?>
<div class="page-head"><div><span class="eyebrow dark">Manajemen Tenant</span><h1><?= is_super_admin($u)?'Tenant & Persetujuan':'HIMA di Bawah '.$u['nama_tenant'] ?></h1><p><?= is_super_admin($u)?'ORMAWA dan HMJ berada pada level yang sama. HIMA berada di bawah HMJ.':'Konfirmasi akun HIMA hanya untuk program studi pada jurusan Anda.' ?></p></div><a class="btn btn-primary" href="<?= e(route_url('register')) ?>">+ Ajukan Akun</a></div>

<section class="panel"><div class="panel-head"><div><h2>Menunggu Persetujuan</h2><p><?= count($approvals) ?> pengajuan perlu ditinjau.</p></div></div>
<div class="approval-cards"><?php if(!$approvals):?><div class="empty-state">Tidak ada pengajuan yang menunggu persetujuan.</div><?php endif;?><?php foreach($approvals as $a):?><article class="approval-card"><div class="approval-main"><span class="tenant-type-chip <?= strtolower($a['tenant_type']) ?>"><?= e($a['tenant_type']) ?></span><h3><?= e($a['nama_tenant']) ?></h3><p><?= e($a['nama_lengkap']??'-') ?> • <?= e($a['email']??'-') ?></p><small>Diajukan <?= e(indo_date($a['requested_at'],'d M Y H:i')) ?></small></div><form method="post" class="approval-actions"><?= csrf_field() ?><input type="hidden" name="approval_id" value="<?= (int)$a['tenant_approval_id'] ?>"><input type="text" name="catatan" placeholder="Catatan (opsional)"><button class="btn btn-success btn-sm" name="action" value="approve_tenant">Setujui</button><button class="btn btn-danger-soft btn-sm" name="action" value="reject_tenant" data-confirm="Tolak pengajuan ini?">Tolak</button></form></article><?php endforeach;?></div></section>

<section class="panel"><div class="panel-head"><div><h2><?= is_super_admin($u)?'Direktori Semua Tenant':'Tenant HIMA' ?></h2><p>Status dan hubungan organisasi dalam arsitektur multi-tenant.</p></div></div>
<div class="table-wrap"><table><thead><tr><th>Tenant</th><th>Tipe</th><th>Jurusan / Prodi</th><th>Parent HMJ</th><th>Admin</th><th>Status</th></tr></thead><tbody>
<?php $rows=is_super_admin($u)?$tenants:$children;if(!$rows):?><tr><td colspan="6" class="empty-cell">Belum ada tenant.</td></tr><?php endif;?>
<?php foreach($rows as $t):?><tr><td><b><?= e($t['nama_tenant']) ?></b><small class="block muted-text"><?= e($t['kode_tenant']) ?></small></td><td><span class="tenant-type-chip <?= strtolower($t['tenant_type']) ?>"><?= e($t['tenant_type']) ?></span></td><td><?= e($t['nama_jurusan']??$t['nama_prodi']??'-') ?><?php if(!empty($t['nama_prodi'])):?><small class="block muted-text"><?= e(($t['jenjang']??'').' '.$t['nama_prodi']) ?></small><?php endif;?></td><td><?= e($t['parent_hmj']??($u['tenant_type']==='HMJ'?$u['nama_tenant']:'-')) ?></td><td><?= (int)$t['admin_count']>0?'<span class="badge badge-success">AKTIF</span>':'<span class="badge badge-warning">BELUM ADA</span>' ?></td><td><?= status_badge($t['status']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
